#!/bin/bash                                                                     

gcc -c main.c  -lglut -lGL -lGLU -lm
gcc -c vectors.c  -lglut -lGL -lGLU -lm
gcc -o vectors main.o vectors.o  -lglut -lGL -lGLU -lm
./vectors
